CREATE TABLE book_status (
                             id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                             book_id BIGINT NOT NULL,
                             status VARCHAR(50) NOT NULL,
                             borrowed_at TIMESTAMP NULL,
                             return_by TIMESTAMP NULL,
                             is_deleted BOOLEAN DEFAULT FALSE
);